-- pg_mcp 0.2.0 (PRD-7 foundation).
--
-- Version stance (PRD-7 §8, pre-1.0): there is no pg_mcp--0.1.0--0.2.0
-- upgrade path. Operators upgrade by `DROP EXTENSION pg_mcp CASCADE` (the
-- local audit tables survive deliberately) and re-CREATE + re-IMPORT. The
-- `sql/pg_mcp--0.1.0.sql` script is retained only for fresh installs pinned
-- to 0.1.0.
--
/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:215
-- pg_mcp::api::mcp_fdw_validator
CREATE  FUNCTION "mcp_fdw_validator"(
	"options" TEXT[], /* Vec < Option < String > > */
	"catalog" oid /* Oid */
) RETURNS void
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mcp_fdw_validator_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:45
-- requires:
--   api::mcp_fdw_validator


-- This hand-written block is emitted before pgrx's `#[pg_schema]` statements,
-- so the schema must exist before the FDW function below lands in it. The
-- later `CREATE SCHEMA IF NOT EXISTS mcp` from the schema modules then skips
-- cleanly (an object the extension already owns).
CREATE SCHEMA IF NOT EXISTS mcp;

-- FR-6.3: register the mcp_fdw foreign-data wrapper so CREATE SERVER and
-- CREATE USER MAPPING run their option validators. The handler's scan/modify
-- routines are PRD-7; planning against a foreign table raises 0A000 today.
--
-- The validator's Rust body is `api::mcp_fdw_validator` (`#[pg_extern]`); its
-- CREATE FUNCTION is written here because `CREATE FOREIGN DATA WRAPPER` below
-- needs it before pgrx emits the schema modules. pgrx later re-emits the same
-- signature as CREATE OR REPLACE FUNCTION, which is a no-op here.
CREATE FUNCTION mcp.mcp_fdw_validator(text[], oid)
  RETURNS void
  AS 'MODULE_PATHNAME', 'mcp_fdw_validator_wrapper'
  LANGUAGE C;

CREATE FUNCTION mcp.mcp_fdw_handler()
  RETURNS fdw_handler
  AS 'MODULE_PATHNAME', 'mcp_fdw_handler'
  LANGUAGE C STRICT;

CREATE FOREIGN DATA WRAPPER mcp_fdw
  HANDLER mcp.mcp_fdw_handler
  VALIDATOR mcp.mcp_fdw_validator;

COMMENT ON FOREIGN DATA WRAPPER mcp_fdw IS
  'Model Context Protocol servers as Postgres foreign servers (pg_mcp)';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:576
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::client::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:632
-- pg_mcp::client::tests::client_identity_is_the_crate_version
CREATE  FUNCTION tests."client_identity_is_the_crate_version"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'client_identity_is_the_crate_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:588
-- pg_mcp::client::tests::bearer_header_shape
CREATE  FUNCTION tests."bearer_header_shape"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bearer_header_shape_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:580
-- pg_mcp::client::tests::bearer_never_prints_its_value
CREATE  FUNCTION tests."bearer_never_prints_its_value"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bearer_never_prints_its_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:638
-- pg_mcp::client::tests::page_items_extracts_the_array_and_the_cursor
CREATE  FUNCTION tests."page_items_extracts_the_array_and_the_cursor"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'page_items_extracts_the_array_and_the_cursor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:625
-- pg_mcp::client::tests::is_error_result_defaults_false
CREATE  FUNCTION tests."is_error_result_defaults_false"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'is_error_result_defaults_false_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:658
-- pg_mcp::client::tests::list_changed_notification_is_observed_and_taken_once
CREATE  FUNCTION tests."list_changed_notification_is_observed_and_taken_once"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_changed_notification_is_observed_and_taken_once_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:607
-- pg_mcp::client::tests::text_content_concatenates_text_parts_only
CREATE  FUNCTION tests."text_content_concatenates_text_parts_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'text_content_concatenates_text_parts_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:674
-- pg_mcp::client::tests::other_notifications_are_ignored
CREATE  FUNCTION tests."other_notifications_are_ignored"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'other_notifications_are_ignored_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:593
-- pg_mcp::client::tests::finish_extracts_result_and_maps_errors
CREATE  FUNCTION tests."finish_extracts_result_and_maps_errors"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'finish_extracts_result_and_maps_errors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:64
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::import::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:115
-- pg_mcp::import::tests::identifiers_are_quoted
CREATE  FUNCTION tests."identifiers_are_quoted"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'identifiers_are_quoted_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:68
-- pg_mcp::import::tests::all_emits_one_statement_per_registry_table
CREATE  FUNCTION tests."all_emits_one_statement_per_registry_table"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'all_emits_one_statement_per_registry_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:76
-- pg_mcp::import::tests::limit_to_and_except_filter_by_table_name
CREATE  FUNCTION tests."limit_to_and_except_filter_by_table_name"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'limit_to_and_except_filter_by_table_name_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:93
-- pg_mcp::import::tests::tool_calls_ddl_matches_the_prd_column_block
CREATE  FUNCTION tests."tool_calls_ddl_matches_the_prd_column_block"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_calls_ddl_matches_the_prd_column_block_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:802
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::tables::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:901
-- pg_mcp::tables::tests::stub_handlers_scan_as_empty_and_refuse_inserts
CREATE  FUNCTION tests."stub_handlers_scan_as_empty_and_refuse_inserts"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stub_handlers_scan_as_empty_and_refuse_inserts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:895
-- pg_mcp::tables::tests::unknown_table_names_do_not_resolve
CREATE  FUNCTION tests."unknown_table_names_do_not_resolve"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unknown_table_names_do_not_resolve_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:951
-- pg_mcp::tables::tests::insert_row_reads_by_column_name
CREATE  FUNCTION tests."insert_row_reads_by_column_name"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'insert_row_reads_by_column_name_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:807
-- pg_mcp::tables::tests::registry_holds_exactly_the_prd_tables
CREATE  FUNCTION tests."registry_holds_exactly_the_prd_tables"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'registry_holds_exactly_the_prd_tables_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:943
-- pg_mcp::tables::tests::stub_handlers_declare_no_pushdown
CREATE  FUNCTION tests."stub_handlers_declare_no_pushdown"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stub_handlers_declare_no_pushdown_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:827
-- pg_mcp::tables::tests::column_names_are_unique_and_non_empty_per_table
CREATE  FUNCTION tests."column_names_are_unique_and_non_empty_per_table"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'column_names_are_unique_and_non_empty_per_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:849
-- pg_mcp::tables::tests::tool_tables_carry_their_prd_columns_and_types
CREATE  FUNCTION tests."tool_tables_carry_their_prd_columns_and_types"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_tables_carry_their_prd_columns_and_types_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:876
-- pg_mcp::tables::tests::type_oids_agree_with_the_sql_spelling
CREATE  FUNCTION tests."type_oids_agree_with_the_sql_spelling"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'type_oids_agree_with_the_sql_spelling_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:74
CREATE SCHEMA IF NOT EXISTS mcp; /* pg_mcp::api::mcp */
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:190
-- pg_mcp::api::mcp::session_info
CREATE  FUNCTION mcp."session_info"(
	"server" TEXT /* & str */
) RETURNS jsonb /* Option < JsonB > */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:121
-- pg_mcp::api::mcp::read_resource
CREATE  FUNCTION mcp."read_resource"(
	"server" TEXT, /* & str */
	"uri" TEXT /* & str */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'read_resource_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:141
-- pg_mcp::api::mcp::refresh
CREATE  FUNCTION mcp."refresh"(
	"server" TEXT /* & str */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'refresh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:82
-- pg_mcp::api::mcp::call_tool
CREATE  FUNCTION mcp."call_tool"(
	"server" TEXT, /* & str */
	"tool" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb, /* Option < JsonB > */
	"on_error" TEXT DEFAULT 'raise' /* & str */
) RETURNS jsonb /* JsonB */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'call_tool_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:183
-- pg_mcp::api::mcp::session_count
CREATE  FUNCTION mcp."session_count"() RETURNS INT /* i32 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:106
-- pg_mcp::api::mcp::get_prompt
CREATE  FUNCTION mcp."get_prompt"(
	"server" TEXT, /* & str */
	"prompt" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_prompt_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:173
-- pg_mcp::api::mcp::session_initialize_count
CREATE  FUNCTION mcp."session_initialize_count"(
	"server" TEXT /* & str */
) RETURNS INT /* Option < i32 > */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_initialize_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:127
-- pg_mcp::api::mcp::complete
CREATE  FUNCTION mcp."complete"(
	"server" TEXT, /* & str */
	"r#ref" jsonb, /* JsonB */
	"argument_name" TEXT, /* & str */
	"argument_value" TEXT /* & str */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:94
-- pg_mcp::api::mcp::call_tool_text
CREATE  FUNCTION mcp."call_tool_text"(
	"server" TEXT, /* & str */
	"tool" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb, /* Option < JsonB > */
	"on_error" TEXT DEFAULT 'raise' /* & str */
) RETURNS TEXT /* Option < String > */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'call_tool_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:157
-- pg_mcp::api::mcp::import
CREATE  FUNCTION mcp."import"(
	"server" TEXT, /* & str */
	"schema" TEXT, /* & str */
	"opts" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS INT /* i32 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:84
CREATE SCHEMA IF NOT EXISTS mcp; /* pg_mcp::mcp */
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:94
-- pg_mcp::mcp::protocol_version
CREATE  FUNCTION mcp."protocol_version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'protocol_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:88
-- pg_mcp::mcp::version
CREATE  FUNCTION mcp."version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:145
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::quals::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:195
-- pg_mcp::quals::tests::matches_json_semantics
CREATE  FUNCTION tests."matches_json_semantics"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'matches_json_semantics_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:185
-- pg_mcp::quals::tests::other_columns_are_never_falsified
CREATE  FUNCTION tests."other_columns_are_never_falsified"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'other_columns_are_never_falsified_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:159
-- pg_mcp::quals::tests::equal_on_primitives_is_supported
CREATE  FUNCTION tests."equal_on_primitives_is_supported"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'equal_on_primitives_is_supported_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:176
-- pg_mcp::quals::tests::nulls_and_nested_sets_are_unsupported
CREATE  FUNCTION tests."nulls_and_nested_sets_are_unsupported"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nulls_and_nested_sets_are_unsupported_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:166
-- pg_mcp::quals::tests::any_equal_with_zero_one_and_n_elements_is_supported
CREATE  FUNCTION tests."any_equal_with_zero_one_and_n_elements_is_supported"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'any_equal_with_zero_one_and_n_elements_is_supported_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:222
-- pg_mcp::quals::tests::fdw_private_round_trips_through_json
CREATE  FUNCTION tests."fdw_private_round_trips_through_json"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fdw_private_round_trips_through_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:213
-- pg_mcp::quals::tests::restricted_values_flattens_sets
CREATE  FUNCTION tests."restricted_values_flattens_sets"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'restricted_values_flattens_sets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:149
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::sse::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:217
-- pg_mcp::sse::tests::truncated_stream_is_08006
CREATE  FUNCTION tests."truncated_stream_is_08006"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'truncated_stream_is_08006_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:224
-- pg_mcp::sse::tests::stream_without_the_wanted_id_is_08006
CREATE  FUNCTION tests."stream_without_the_wanted_id_is_08006"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_without_the_wanted_id_is_08006_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:167
-- pg_mcp::sse::tests::multi_line_data_is_joined_with_newlines
CREATE  FUNCTION tests."multi_line_data_is_joined_with_newlines"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'multi_line_data_is_joined_with_newlines_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:260
-- pg_mcp::sse::tests::interrupt_hook_runs_between_events
CREATE  FUNCTION tests."interrupt_hook_runs_between_events"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'interrupt_hook_runs_between_events_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:231
-- pg_mcp::sse::tests::non_json_frames_are_skipped_not_fatal
CREATE  FUNCTION tests."non_json_frames_are_skipped_not_fatal"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'non_json_frames_are_skipped_not_fatal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:280
-- pg_mcp::sse::tests::a_cancelling_interrupt_hook_aborts_the_read
CREATE  FUNCTION tests."a_cancelling_interrupt_hook_aborts_the_read"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_cancelling_interrupt_hook_aborts_the_read_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:329
-- pg_mcp::sse::tests::observer_panics_do_not_bypass_the_match
CREATE  FUNCTION tests."observer_panics_do_not_bypass_the_match"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'observer_panics_do_not_bypass_the_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:292
-- pg_mcp::sse::tests::observer_sees_skipped_frames_including_notifications
CREATE  FUNCTION tests."observer_sees_skipped_frames_including_notifications"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'observer_sees_skipped_frames_including_notifications_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:207
-- pg_mcp::sse::tests::string_ids_still_match
CREATE  FUNCTION tests."string_ids_still_match"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'string_ids_still_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:175
-- pg_mcp::sse::tests::ignores_comments_event_and_id_lines
CREATE  FUNCTION tests."ignores_comments_event_and_id_lines"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ignores_comments_event_and_id_lines_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:245
-- pg_mcp::sse::tests::deadline_is_total_across_the_stream
CREATE  FUNCTION tests."deadline_is_total_across_the_stream"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'deadline_is_total_across_the_stream_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:157
-- pg_mcp::sse::tests::single_event
CREATE  FUNCTION tests."single_event"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'single_event_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:191
-- pg_mcp::sse::tests::skips_frames_for_other_ids_and_notifications
CREATE  FUNCTION tests."skips_frames_for_other_ids_and_notifications"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'skips_frames_for_other_ids_and_notifications_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:352
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::options::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:422
-- pg_mcp::options::tests::plain_http_is_loopback_only
CREATE  FUNCTION tests."plain_http_is_loopback_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'plain_http_is_loopback_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:499
-- pg_mcp::options::tests::audit_table_must_be_schema_qualified
CREATE  FUNCTION tests."audit_table_must_be_schema_qualified"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'audit_table_must_be_schema_qualified_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:384
-- pg_mcp::options::tests::applies_documented_defaults
CREATE  FUNCTION tests."applies_documented_defaults"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'applies_documented_defaults_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:541
-- pg_mcp::options::tests::user_mapping_errors_never_echo_the_token
CREATE  FUNCTION tests."user_mapping_errors_never_echo_the_token"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'user_mapping_errors_never_echo_the_token_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:474
-- pg_mcp::options::tests::timeout_boundaries_are_inclusive
CREATE  FUNCTION tests."timeout_boundaries_are_inclusive"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'timeout_boundaries_are_inclusive_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:395
-- pg_mcp::options::tests::cache_ttl_zero_disables_and_negatives_are_rejected
CREATE  FUNCTION tests."cache_ttl_zero_disables_and_negatives_are_rejected"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cache_ttl_zero_disables_and_negatives_are_rejected_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:446
-- pg_mcp::options::tests::rejects_bad_enum_and_range_values
CREATE  FUNCTION tests."rejects_bad_enum_and_range_values"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rejects_bad_enum_and_range_values_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:429
-- pg_mcp::options::tests::auth_none_is_loopback_only
CREATE  FUNCTION tests."auth_none_is_loopback_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'auth_none_is_loopback_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:414
-- pg_mcp::options::tests::url_is_required_and_must_be_absolute_http
CREATE  FUNCTION tests."url_is_required_and_must_be_absolute_http"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'url_is_required_and_must_be_absolute_http_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:363
-- pg_mcp::options::tests::accepts_the_full_prd_option_set
CREATE  FUNCTION tests."accepts_the_full_prd_option_set"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'accepts_the_full_prd_option_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:518
-- pg_mcp::options::tests::user_mapping_accepts_exactly_one_credential
CREATE  FUNCTION tests."user_mapping_accepts_exactly_one_credential"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'user_mapping_accepts_exactly_one_credential_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:488
-- pg_mcp::options::tests::rejects_unknown_server_option
CREATE  FUNCTION tests."rejects_unknown_server_option"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rejects_unknown_server_option_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:394
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::session::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:406
-- pg_mcp::session::tests::validator_option_array_splits_on_the_first_equals
CREATE  FUNCTION tests."validator_option_array_splits_on_the_first_equals"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'validator_option_array_splits_on_the_first_equals_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:423
-- pg_mcp::session::tests::params_object_defaults_to_empty
CREATE  FUNCTION tests."params_object_defaults_to_empty"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'params_object_defaults_to_empty_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:446
-- pg_mcp::session::tests::current_user_oid_is_a_real_role
CREATE  FUNCTION tests."current_user_oid_is_a_real_role"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'current_user_oid_is_a_real_role_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:440
-- pg_mcp::session::tests::dropping_an_absent_session_reports_false
CREATE  FUNCTION tests."dropping_an_absent_session_reports_false"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dropping_an_absent_session_reports_false_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:399
-- pg_mcp::session::tests::unknown_foreign_server_is_42704
CREATE  FUNCTION tests."unknown_foreign_server_is_42704"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unknown_foreign_server_is_42704_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:430
-- pg_mcp::session::tests::session_map_starts_empty_in_a_fresh_backend
CREATE  FUNCTION tests."session_map_starts_empty_in_a_fresh_backend"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_map_starts_empty_in_a_fresh_backend_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:924
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::fdw::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1033
-- pg_mcp::fdw::tests::insert_into_a_stub_table_raises_0a000
CREATE  FUNCTION tests."insert_into_a_stub_table_raises_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'insert_into_a_stub_table_raises_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1020
-- pg_mcp::fdw::tests::a_role_without_a_user_mapping_still_scans_an_auth_none_server
CREATE  FUNCTION tests."a_role_without_a_user_mapping_still_scans_an_auth_none_server"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_role_without_a_user_mapping_still_scans_an_auth_none_server_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:968
-- pg_mcp::fdw::tests::import_creates_the_registry_tables_and_tools_scans_as_empty
CREATE  FUNCTION tests."import_creates_the_registry_tables_and_tools_scans_as_empty"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_creates_the_registry_tables_and_tools_scans_as_empty_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1066
-- pg_mcp::fdw::tests::explain_of_a_scan_does_not_execute_the_handler
CREATE  FUNCTION tests."explain_of_a_scan_does_not_execute_the_handler"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'explain_of_a_scan_does_not_execute_the_handler_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:997
-- pg_mcp::fdw::tests::import_honors_limit_to_and_unknown_remote_schema_is_3f000
CREATE  FUNCTION tests."import_honors_limit_to_and_unknown_remote_schema_is_3f000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_honors_limit_to_and_unknown_remote_schema_is_3f000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1055
-- pg_mcp::fdw::tests::a_foreign_table_outside_the_registry_raises_0a000
CREATE  FUNCTION tests."a_foreign_table_outside_the_registry_raises_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_foreign_table_outside_the_registry_raises_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1045
-- pg_mcp::fdw::tests::update_and_delete_on_tool_calls_raise_0a000
CREATE  FUNCTION tests."update_and_delete_on_tool_calls_raise_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'update_and_delete_on_tool_calls_raise_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:204
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::errors::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:282
-- pg_mcp::errors::tests::authz_shaped_rpc_errors_become_42501
CREATE  FUNCTION tests."authz_shaped_rpc_errors_become_42501"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'authz_shaped_rpc_errors_become_42501_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:276
-- pg_mcp::errors::tests::rpc_error_carries_server_message
CREATE  FUNCTION tests."rpc_error_carries_server_message"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rpc_error_carries_server_message_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:296
-- pg_mcp::errors::tests::expired_session_detection
CREATE  FUNCTION tests."expired_session_detection"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'expired_session_detection_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:208
-- pg_mcp::errors::tests::errcode_table_matches_prd_6_4_7
CREATE  FUNCTION tests."errcode_table_matches_prd_6_4_7"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'errcode_table_matches_prd_6_4_7_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:222
-- pg_mcp::errors::tests::errcode_table_covers_the_full_prd_7_4_9_set
CREATE  FUNCTION tests."errcode_table_covers_the_full_prd_7_4_9_set"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'errcode_table_covers_the_full_prd_7_4_9_set_wrapper';
/* </end connected objects> */

