-- pg_mcp 0.3.0 (PRD-8: per-tool codegen — tables, functions, views, type map).
--
-- Generated from the crate with:
--   cargo pgrx schema --no-default-features --features "pg18 pg_test"
-- (with MODULE_PATHNAME retained; run-tests.sh rewrites it to $libdir/pg_mcp
-- for its throwaway cluster). The 0.2.0 → 0.3.0 upgrade path is the
-- hand-written pg_mcp--0.2.0--0.3.0.sql alongside this file.

/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:465
-- pg_mcp::api::mcp_fdw_validator
CREATE  FUNCTION "mcp_fdw_validator"(
	"options" TEXT[], /* Vec < Option < String > > */
	"catalog" oid /* Oid */
) RETURNS void
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mcp_fdw_validator_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:46
-- requires:
--   api::mcp_fdw_validator


-- This hand-written block is emitted before pgrx's `#[pg_schema]` statements,
-- so the schema must exist before the FDW function below lands in it. The
-- later `CREATE SCHEMA IF NOT EXISTS mcp` from the schema modules then skips
-- cleanly (an object the extension already owns).
CREATE SCHEMA IF NOT EXISTS mcp;

-- FR-6.3: register the mcp_fdw foreign-data wrapper so CREATE SERVER and
-- CREATE USER MAPPING run their option validators. The handler's scan/modify
-- routines are PRD-7; planning against a foreign table raises 0A000 today.
--
-- The validator's Rust body is `api::mcp_fdw_validator` (`#[pg_extern]`); its
-- CREATE FUNCTION is written here because `CREATE FOREIGN DATA WRAPPER` below
-- needs it before pgrx emits the schema modules. pgrx later re-emits the same
-- signature as CREATE OR REPLACE FUNCTION, which is a no-op here.
CREATE FUNCTION mcp.mcp_fdw_validator(text[], oid)
  RETURNS void
  AS 'MODULE_PATHNAME', 'mcp_fdw_validator_wrapper'
  LANGUAGE C;

CREATE FUNCTION mcp.mcp_fdw_handler()
  RETURNS fdw_handler
  AS 'MODULE_PATHNAME', 'mcp_fdw_handler'
  LANGUAGE C STRICT;

CREATE FOREIGN DATA WRAPPER mcp_fdw
  HANDLER mcp.mcp_fdw_handler
  VALIDATOR mcp.mcp_fdw_validator;

COMMENT ON FOREIGN DATA WRAPPER mcp_fdw IS
  'Model Context Protocol servers as Postgres foreign servers (pg_mcp)';

-- PRD-8 section 4.6: the per-tool generation bookkeeping. Names and
-- provenance only (AP-P7) -- never a copy of a tool schema; regeneration
-- always re-reads from the server. Lives in this hand-written block because
-- it must follow the CREATE SCHEMA mcp above, and extension_sql blocks
-- cannot depend on each other's ordering. The same DDL is mirrored in the
-- hand-written pg_mcp--0.2.0--0.3.0.sql upgrade script; the shape's single
-- source is codegen::registry::CREATE_TABLE_SQL.
CREATE TABLE mcp.generated (
  server text NOT NULL,
  schema text NOT NULL,
  kind text NOT NULL,
  name text NOT NULL,
  tool text NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (schema, name)
);

COMMENT ON TABLE mcp.generated IS
  'Per-tool generation bookkeeping (PRD-8 section 4.6): names and provenance of the SQL objects pg_mcp created from MCP tool definitions. Never a copy of a tool schema - regeneration always re-reads from the server.';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/table.rs:139
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::table::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/table.rs:197
-- pg_mcp::codegen::table::tests::the_gate_and_extra_options_are_stamped_in_order
CREATE  FUNCTION tests."the_gate_and_extra_options_are_stamped_in_order"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'the_gate_and_extra_options_are_stamped_in_order_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/table.rs:240
-- pg_mcp::codegen::table::tests::no_output_schema_means_content_and_is_error_only
CREATE  FUNCTION tests."no_output_schema_means_content_and_is_error_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'no_output_schema_means_content_and_is_error_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/table.rs:223
-- pg_mcp::codegen::table::tests::reserved_word_names_are_quoted_not_renamed
CREATE  FUNCTION tests."reserved_word_names_are_quoted_not_renamed"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reserved_word_names_are_quoted_not_renamed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/table.rs:146
-- pg_mcp::codegen::table::tests::the_prd_example_table_ddl_is_exact
CREATE  FUNCTION tests."the_prd_example_table_ddl_is_exact"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'the_prd_example_table_ddl_is_exact_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/table.rs:257
-- pg_mcp::codegen::table::tests::enum_properties_get_column_comments
CREATE  FUNCTION tests."enum_properties_get_column_comments"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'enum_properties_get_column_comments_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:204
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::errors::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:276
-- pg_mcp::errors::tests::rpc_error_carries_server_message
CREATE  FUNCTION tests."rpc_error_carries_server_message"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rpc_error_carries_server_message_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:208
-- pg_mcp::errors::tests::errcode_table_matches_prd_6_4_7
CREATE  FUNCTION tests."errcode_table_matches_prd_6_4_7"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'errcode_table_matches_prd_6_4_7_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:222
-- pg_mcp::errors::tests::errcode_table_covers_the_full_prd_7_4_9_set
CREATE  FUNCTION tests."errcode_table_covers_the_full_prd_7_4_9_set"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'errcode_table_covers_the_full_prd_7_4_9_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:296
-- pg_mcp::errors::tests::expired_session_detection
CREATE  FUNCTION tests."expired_session_detection"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'expired_session_detection_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/errors.rs:282
-- pg_mcp::errors::tests::authz_shaped_rpc_errors_become_42501
CREATE  FUNCTION tests."authz_shaped_rpc_errors_become_42501"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'authz_shaped_rpc_errors_become_42501_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:459
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::tables::tool_calls::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:508
-- pg_mcp::tables::tool_calls::tests::tool_calls_log_partitions_per_server_and_user
CREATE  FUNCTION tests."tool_calls_log_partitions_per_server_and_user"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_calls_log_partitions_per_server_and_user_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:989
-- pg_mcp::tables::tool_calls::tests::select_before_any_insert_scans_empty_and_never_connects
CREATE  FUNCTION tests."select_before_any_insert_scans_empty_and_never_connects"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'select_before_any_insert_scans_empty_and_never_connects_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:857
-- pg_mcp::tables::tool_calls::tests::a_failing_tool_mid_statement_is_a_row_not_an_exception
CREATE  FUNCTION tests."a_failing_tool_mid_statement_is_a_row_not_an_exception"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_failing_tool_mid_statement_is_a_row_not_an_exception_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:823
-- pg_mcp::tables::tool_calls::tests::t4_arguments_defaults_to_empty_and_output_columns_on_input_are_
CREATE  FUNCTION tests."t4_arguments_defaults_to_empty_and_output_columns_on_input_are_"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 't4_arguments_defaults_to_empty_and_output_columns_on_input_are__wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:911
-- pg_mcp::tables::tool_calls::tests::tool_null_raises_23502
CREATE  FUNCTION tests."tool_null_raises_23502"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_null_raises_23502_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:486
-- pg_mcp::tables::tool_calls::tests::tool_calls_log_is_capped_at_1000_and_newest_first
CREATE  FUNCTION tests."tool_calls_log_is_capped_at_1000_and_newest_first"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_calls_log_is_capped_at_1000_and_newest_first_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:998
-- pg_mcp::tables::tool_calls::tests::update_and_delete_on_tool_calls_still_raise_0a000
CREATE  FUNCTION tests."update_and_delete_on_tool_calls_still_raise_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'update_and_delete_on_tool_calls_still_raise_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:1068
-- pg_mcp::tables::tool_calls::tests::audit_shape_mismatch_raises_42804_naming_the_column
CREATE  FUNCTION tests."audit_shape_mismatch_raises_42804_naming_the_column"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'audit_shape_mismatch_raises_42804_naming_the_column_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:957
-- pg_mcp::tables::tool_calls::tests::select_reads_the_log_with_zero_network_io
CREATE  FUNCTION tests."select_reads_the_log_with_zero_network_io"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'select_reads_the_log_with_zero_network_io_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:1013
-- pg_mcp::tables::tool_calls::tests::audit_appends_completed_calls_transactionally
CREATE  FUNCTION tests."audit_appends_completed_calls_transactionally"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'audit_appends_completed_calls_transactionally_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:1127
-- pg_mcp::tables::tool_calls::tests::audit_is_off_by_default
CREATE  FUNCTION tests."audit_is_off_by_default"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'audit_is_off_by_default_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:566
-- pg_mcp::tables::tool_calls::tests::now_pg_micros_is_past_the_pg_epoch_by_decades
CREATE  FUNCTION tests."now_pg_micros_is_past_the_pg_epoch_by_decades"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'now_pg_micros_is_past_the_pg_epoch_by_decades_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:556
-- pg_mcp::tables::tool_calls::tests::uuids_are_v4_and_unique
CREATE  FUNCTION tests."uuids_are_v4_and_unique"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'uuids_are_v4_and_unique_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:783
-- pg_mcp::tables::tool_calls::tests::insert_performs_one_tools_call_and_fills_every_output_column
CREATE  FUNCTION tests."insert_performs_one_tools_call_and_fills_every_output_column"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'insert_performs_one_tools_call_and_fills_every_output_column_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:532
-- pg_mcp::tables::tool_calls::tests::log_qual_filter_matches_tool_and_id
CREATE  FUNCTION tests."log_qual_filter_matches_tool_and_id"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'log_qual_filter_matches_tool_and_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/tool_calls.rs:929
-- pg_mcp::tables::tool_calls::tests::protocol_failures_raise_per_4_9
CREATE  FUNCTION tests."protocol_failures_raise_per_4_9"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'protocol_failures_raise_per_4_9_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:352
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::options::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:541
-- pg_mcp::options::tests::user_mapping_errors_never_echo_the_token
CREATE  FUNCTION tests."user_mapping_errors_never_echo_the_token"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'user_mapping_errors_never_echo_the_token_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:363
-- pg_mcp::options::tests::accepts_the_full_prd_option_set
CREATE  FUNCTION tests."accepts_the_full_prd_option_set"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'accepts_the_full_prd_option_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:488
-- pg_mcp::options::tests::rejects_unknown_server_option
CREATE  FUNCTION tests."rejects_unknown_server_option"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rejects_unknown_server_option_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:384
-- pg_mcp::options::tests::applies_documented_defaults
CREATE  FUNCTION tests."applies_documented_defaults"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'applies_documented_defaults_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:499
-- pg_mcp::options::tests::audit_table_must_be_schema_qualified
CREATE  FUNCTION tests."audit_table_must_be_schema_qualified"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'audit_table_must_be_schema_qualified_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:395
-- pg_mcp::options::tests::cache_ttl_zero_disables_and_negatives_are_rejected
CREATE  FUNCTION tests."cache_ttl_zero_disables_and_negatives_are_rejected"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cache_ttl_zero_disables_and_negatives_are_rejected_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:422
-- pg_mcp::options::tests::plain_http_is_loopback_only
CREATE  FUNCTION tests."plain_http_is_loopback_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'plain_http_is_loopback_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:518
-- pg_mcp::options::tests::user_mapping_accepts_exactly_one_credential
CREATE  FUNCTION tests."user_mapping_accepts_exactly_one_credential"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'user_mapping_accepts_exactly_one_credential_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:414
-- pg_mcp::options::tests::url_is_required_and_must_be_absolute_http
CREATE  FUNCTION tests."url_is_required_and_must_be_absolute_http"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'url_is_required_and_must_be_absolute_http_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:474
-- pg_mcp::options::tests::timeout_boundaries_are_inclusive
CREATE  FUNCTION tests."timeout_boundaries_are_inclusive"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'timeout_boundaries_are_inclusive_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:429
-- pg_mcp::options::tests::auth_none_is_loopback_only
CREATE  FUNCTION tests."auth_none_is_loopback_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'auth_none_is_loopback_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/options.rs:446
-- pg_mcp::options::tests::rejects_bad_enum_and_range_values
CREATE  FUNCTION tests."rejects_bad_enum_and_range_values"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'rejects_bad_enum_and_range_values_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:269
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::ident::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:414
-- pg_mcp::codegen::ident::tests::sha256_matches_the_published_test_vectors
CREATE  FUNCTION tests."sha256_matches_the_published_test_vectors"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'sha256_matches_the_published_test_vectors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:351
-- pg_mcp::codegen::ident::tests::colliding_names_get_deterministic_distinct_suffixes
CREATE  FUNCTION tests."colliding_names_get_deterministic_distinct_suffixes"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'colliding_names_get_deterministic_distinct_suffixes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:302
-- pg_mcp::codegen::ident::tests::prefix_is_prepended_and_counts_toward_the_length_rule
CREATE  FUNCTION tests."prefix_is_prepended_and_counts_toward_the_length_rule"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prefix_is_prepended_and_counts_toward_the_length_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:321
-- pg_mcp::codegen::ident::tests::t0_long_names_truncate_to_63_bytes_with_a_deterministic_hash_su
CREATE  FUNCTION tests."t0_long_names_truncate_to_63_bytes_with_a_deterministic_hash_su"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 't0_long_names_truncate_to_63_bytes_with_a_deterministic_hash_su_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:386
-- pg_mcp::codegen::ident::tests::hostile_names_always_produce_valid_identifiers
CREATE  FUNCTION tests."hostile_names_always_produce_valid_identifiers"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hostile_names_always_produce_valid_identifiers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:274
-- pg_mcp::codegen::ident::tests::derivation_rules_split_case_and_strip_separators
CREATE  FUNCTION tests."derivation_rules_split_case_and_strip_separators"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'derivation_rules_split_case_and_strip_separators_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:309
-- pg_mcp::codegen::ident::tests::reserved_words_are_recognized_and_survive_unrenamed
CREATE  FUNCTION tests."reserved_words_are_recognized_and_survive_unrenamed"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reserved_words_are_recognized_and_survive_unrenamed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/ident.rs:342
-- pg_mcp::codegen::ident::tests::prefix_applied_names_also_respect_the_63_byte_limit
CREATE  FUNCTION tests."prefix_applied_names_also_respect_the_63_byte_limit"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prefix_applied_names_also_respect_the_63_byte_limit_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:248
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::function::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:394
-- pg_mcp::codegen::function::tests::reserved_word_parameters_and_names_are_quoted
CREATE  FUNCTION tests."reserved_word_parameters_and_names_are_quoted"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'reserved_word_parameters_and_names_are_quoted_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:377
-- pg_mcp::codegen::function::tests::a_tool_with_no_outputs_returns_the_whole_result_as_jsonb
CREATE  FUNCTION tests."a_tool_with_no_outputs_returns_the_whole_result_as_jsonb"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_tool_with_no_outputs_returns_the_whole_result_as_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:409
-- pg_mcp::codegen::function::tests::tools_without_metadata_generate_no_comment
CREATE  FUNCTION tests."tools_without_metadata_generate_no_comment"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tools_without_metadata_generate_no_comment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:355
-- pg_mcp::codegen::function::tests::non_readonly_fanout_tool_still_returns_the_typed_shape
CREATE  FUNCTION tests."non_readonly_fanout_tool_still_returns_the_typed_shape"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'non_readonly_fanout_tool_still_returns_the_typed_shape_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:327
-- pg_mcp::codegen::function::tests::non_readonly_function_inserts_through_a_cte
CREATE  FUNCTION tests."non_readonly_function_inserts_through_a_cte"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'non_readonly_function_inserts_through_a_cte_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:294
-- pg_mcp::codegen::function::tests::readonly_fanout_function_is_exact
CREATE  FUNCTION tests."readonly_fanout_function_is_exact"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'readonly_fanout_function_is_exact_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/function.rs:429
-- pg_mcp::codegen::function::tests::drop_function_carries_the_identity_types
CREATE  FUNCTION tests."drop_function_carries_the_identity_types"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_function_carries_the_identity_types_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:203
CREATE SCHEMA IF NOT EXISTS mcp; /* pg_mcp::api::mcp */
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:368
-- pg_mcp::api::mcp::generate_functions
CREATE  FUNCTION mcp."generate_functions"(
	"server" TEXT, /* & str */
	"schema" TEXT, /* & str */
	"opts" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS TABLE (
	"generated" INT,  /* i32 */
	"skipped" INT,  /* i32 */
	"skipped_tools" TEXT[]  /* Vec < Option < String > > */
)
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'generate_functions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:270
-- pg_mcp::api::mcp::refresh
CREATE  FUNCTION mcp."refresh"(
	"server" TEXT /* & str */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'refresh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:433
-- pg_mcp::api::mcp::session_count
CREATE  FUNCTION mcp."session_count"() RETURNS INT /* i32 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:235
-- pg_mcp::api::mcp::get_prompt
CREATE  FUNCTION mcp."get_prompt"(
	"server" TEXT, /* & str */
	"prompt" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_prompt_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:223
-- pg_mcp::api::mcp::call_tool_text
CREATE  FUNCTION mcp."call_tool_text"(
	"server" TEXT, /* & str */
	"tool" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb, /* Option < JsonB > */
	"on_error" TEXT DEFAULT 'raise' /* & str */
) RETURNS TEXT /* Option < String > */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'call_tool_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:250
-- pg_mcp::api::mcp::read_resource
CREATE  FUNCTION mcp."read_resource"(
	"server" TEXT, /* & str */
	"uri" TEXT /* & str */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'read_resource_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:440
-- pg_mcp::api::mcp::session_info
CREATE  FUNCTION mcp."session_info"(
	"server" TEXT /* & str */
) RETURNS jsonb /* Option < JsonB > */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:313
-- pg_mcp::api::mcp::import
CREATE  FUNCTION mcp."import"(
	"server" TEXT, /* & str */
	"schema" TEXT, /* & str */
	"opts" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS INT /* i32 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:256
-- pg_mcp::api::mcp::complete
CREATE  FUNCTION mcp."complete"(
	"server" TEXT, /* & str */
	"r#ref" jsonb, /* JsonB */
	"argument_name" TEXT, /* & str */
	"argument_value" TEXT /* & str */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:211
-- pg_mcp::api::mcp::call_tool
CREATE  FUNCTION mcp."call_tool"(
	"server" TEXT, /* & str */
	"tool" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb, /* Option < JsonB > */
	"on_error" TEXT DEFAULT 'raise' /* & str */
) RETURNS jsonb /* JsonB */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'call_tool_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:423
-- pg_mcp::api::mcp::session_initialize_count
CREATE  FUNCTION mcp."session_initialize_count"(
	"server" TEXT /* & str */
) RETURNS INT /* Option < i32 > */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_initialize_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:576
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::client::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:607
-- pg_mcp::client::tests::text_content_concatenates_text_parts_only
CREATE  FUNCTION tests."text_content_concatenates_text_parts_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'text_content_concatenates_text_parts_only_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:632
-- pg_mcp::client::tests::client_identity_is_the_crate_version
CREATE  FUNCTION tests."client_identity_is_the_crate_version"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'client_identity_is_the_crate_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:625
-- pg_mcp::client::tests::is_error_result_defaults_false
CREATE  FUNCTION tests."is_error_result_defaults_false"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'is_error_result_defaults_false_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:638
-- pg_mcp::client::tests::page_items_extracts_the_array_and_the_cursor
CREATE  FUNCTION tests."page_items_extracts_the_array_and_the_cursor"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'page_items_extracts_the_array_and_the_cursor_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:674
-- pg_mcp::client::tests::other_notifications_are_ignored
CREATE  FUNCTION tests."other_notifications_are_ignored"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'other_notifications_are_ignored_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:658
-- pg_mcp::client::tests::list_changed_notification_is_observed_and_taken_once
CREATE  FUNCTION tests."list_changed_notification_is_observed_and_taken_once"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_changed_notification_is_observed_and_taken_once_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:580
-- pg_mcp::client::tests::bearer_never_prints_its_value
CREATE  FUNCTION tests."bearer_never_prints_its_value"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bearer_never_prints_its_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:593
-- pg_mcp::client::tests::finish_extracts_result_and_maps_errors
CREATE  FUNCTION tests."finish_extracts_result_and_maps_errors"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'finish_extracts_result_and_maps_errors_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/client.rs:588
-- pg_mcp::client::tests::bearer_header_shape
CREATE  FUNCTION tests."bearer_header_shape"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bearer_header_shape_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:179
CREATE SCHEMA IF NOT EXISTS cache_test; /* pg_mcp::cache::cache_test */
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:339
-- pg_mcp::cache::cache_test::fetch_errors_are_never_cached
CREATE  FUNCTION cache_test."fetch_errors_are_never_cached"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fetch_errors_are_never_cached_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:277
-- pg_mcp::cache::cache_test::drop_clears_every_slice_and_refetches
CREATE  FUNCTION cache_test."drop_clears_every_slice_and_refetches"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_clears_every_slice_and_refetches_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:195
-- pg_mcp::cache::cache_test::cache_hit_within_ttl_and_refetch_after_expiry
CREATE  FUNCTION cache_test."cache_hit_within_ttl_and_refetch_after_expiry"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cache_hit_within_ttl_and_refetch_after_expiry_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:317
-- pg_mcp::cache::cache_test::ttl_zero_disables_caching
CREATE  FUNCTION cache_test."ttl_zero_disables_caching"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ttl_zero_disables_caching_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:299
-- pg_mcp::cache::cache_test::drop_tools_only_drops_the_tools_slice
CREATE  FUNCTION cache_test."drop_tools_only_drops_the_tools_slice"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_tools_only_drops_the_tools_slice_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/cache.rs:234
-- pg_mcp::cache::cache_test::per_user_isolation_two_roles_never_share_entries
CREATE  FUNCTION cache_test."per_user_isolation_two_roles_never_share_entries"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_user_isolation_two_roles_never_share_entries_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:143
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::types::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:152
-- pg_mcp::codegen::types::tests::the_prd_type_table_maps_exactly
CREATE  FUNCTION tests."the_prd_type_table_maps_exactly"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'the_prd_type_table_maps_exactly_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:209
-- pg_mcp::codegen::types::tests::composition_keywords_and_refs_fall_back_to_jsonb
CREATE  FUNCTION tests."composition_keywords_and_refs_fall_back_to_jsonb"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'composition_keywords_and_refs_fall_back_to_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:183
-- pg_mcp::codegen::types::tests::union_schemas_take_the_single_non_null_branch
CREATE  FUNCTION tests."union_schemas_take_the_single_non_null_branch"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'union_schemas_take_the_single_non_null_branch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:228
-- pg_mcp::codegen::types::tests::absent_and_malformed_schemas_are_jsonb
CREATE  FUNCTION tests."absent_and_malformed_schemas_are_jsonb"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'absent_and_malformed_schemas_are_jsonb_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:289
-- pg_mcp::codegen::types::tests::enum_hint_renders_permitted_values_for_the_column_comment
CREATE  FUNCTION tests."enum_hint_renders_permitted_values_for_the_column_comment"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'enum_hint_renders_permitted_values_for_the_column_comment_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:252
-- pg_mcp::codegen::types::tests::required_set_reads_the_required_array
CREATE  FUNCTION tests."required_set_reads_the_required_array"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'required_set_reads_the_required_array_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/types.rs:274
-- pg_mcp::codegen::types::tests::properties_preserve_published_order
CREATE  FUNCTION tests."properties_preserve_published_order"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'properties_preserve_published_order_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/view.rs:55
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::view::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/view.rs:175
-- pg_mcp::codegen::view::tests::drop_view_is_restrict
CREATE  FUNCTION tests."drop_view_is_restrict"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_view_is_restrict_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/view.rs:102
-- pg_mcp::codegen::view::tests::required_inputs_block_the_view
CREATE  FUNCTION tests."required_inputs_block_the_view"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'required_inputs_block_the_view_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/view.rs:157
-- pg_mcp::codegen::view::tests::view_without_output_schema_projects_the_bare_pair
CREATE  FUNCTION tests."view_without_output_schema_projects_the_bare_pair"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'view_without_output_schema_projects_the_bare_pair_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/view.rs:69
-- pg_mcp::codegen::view::tests::eligible_read_only_tools_get_the_flat_view
CREATE  FUNCTION tests."eligible_read_only_tools_get_the_flat_view"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'eligible_read_only_tools_get_the_flat_view_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/view.rs:120
-- pg_mcp::codegen::view::tests::gated_tables_get_no_view
CREATE  FUNCTION tests."gated_tables_get_no_view"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'gated_tables_get_no_view_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:501
CREATE SCHEMA IF NOT EXISTS catalog_test; /* pg_mcp::tables::catalog::catalog_test */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:774
-- pg_mcp::tables::catalog::catalog_test::prompts_and_prompt_arguments_flatten_with_index
CREATE  FUNCTION catalog_test."prompts_and_prompt_arguments_flatten_with_index"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prompts_and_prompt_arguments_flatten_with_index_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:888
-- pg_mcp::tables::catalog::catalog_test::refresh_drops_the_catalog_cache_and_the_session
CREATE  FUNCTION catalog_test."refresh_drops_the_catalog_cache_and_the_session"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'refresh_drops_the_catalog_cache_and_the_session_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:624
-- pg_mcp::tables::catalog::catalog_test::server_table_reports_the_handshake_and_identity
CREATE  FUNCTION catalog_test."server_table_reports_the_handshake_and_identity"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'server_table_reports_the_handshake_and_identity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:959
-- pg_mcp::tables::catalog::catalog_test::cross_role_cache_bleed_is_impossible
CREATE  FUNCTION catalog_test."cross_role_cache_bleed_is_impossible"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cross_role_cache_bleed_is_impossible_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:1060
-- pg_mcp::tables::catalog::catalog_test::an_unreachable_server_fails_the_scan_with_08006
CREATE  FUNCTION catalog_test."an_unreachable_server_fails_the_scan_with_08006"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'an_unreachable_server_fails_the_scan_with_08006_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:728
-- pg_mcp::tables::catalog::catalog_test::cursor_following_exhausts_multi_page_lists
CREATE  FUNCTION catalog_test."cursor_following_exhausts_multi_page_lists"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cursor_following_exhausts_multi_page_lists_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:868
-- pg_mcp::tables::catalog::catalog_test::short_ttl_refetches_and_zero_ttl_never_caches
CREATE  FUNCTION catalog_test."short_ttl_refetches_and_zero_ttl_never_caches"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'short_ttl_refetches_and_zero_ttl_never_caches_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:698
-- pg_mcp::tables::catalog::catalog_test::name_quals_filter_after_fetch_and_the_list_is_cached
CREATE  FUNCTION catalog_test."name_quals_filter_after_fetch_and_the_list_is_cached"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'name_quals_filter_after_fetch_and_the_list_is_cached_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:657
-- pg_mcp::tables::catalog::catalog_test::tools_table_maps_the_full_spec
CREATE  FUNCTION catalog_test."tools_table_maps_the_full_spec"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tools_table_maps_the_full_spec_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:754
-- pg_mcp::tables::catalog::catalog_test::method_not_found_is_fail_open_and_siblings_survive
CREATE  FUNCTION catalog_test."method_not_found_is_fail_open_and_siblings_survive"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'method_not_found_is_fail_open_and_siblings_survive_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:816
-- pg_mcp::tables::catalog::catalog_test::resources_and_templates_map_mime_size_and_meta
CREATE  FUNCTION catalog_test."resources_and_templates_map_mime_size_and_meta"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'resources_and_templates_map_mime_size_and_meta_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/catalog.rs:918
-- pg_mcp::tables::catalog::catalog_test::list_changed_notification_drops_the_cached_tools_slice
CREATE  FUNCTION catalog_test."list_changed_notification_drops_the_cached_tools_slice"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'list_changed_notification_drops_the_cached_tools_slice_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:624
CREATE SCHEMA IF NOT EXISTS live_tests; /* pg_mcp::tables::per_tool::live_tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1055
-- pg_mcp::tables::per_tool::live_tests::typed_functions_and_views_generate_and_are_callable
CREATE  FUNCTION live_tests."typed_functions_and_views_generate_and_are_callable"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'typed_functions_and_views_generate_and_are_callable_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1275
-- pg_mcp::tables::per_tool::live_tests::invoke_on_select_all_promotes_with_a_listing_none_demotes
CREATE  FUNCTION live_tests."invoke_on_select_all_promotes_with_a_listing_none_demotes"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'invoke_on_select_all_promotes_with_a_listing_none_demotes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:987
-- pg_mcp::tables::per_tool::live_tests::the_gate_blocks_selects_and_names_the_insert_alternative
CREATE  FUNCTION live_tests."the_gate_blocks_selects_and_names_the_insert_alternative"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'the_gate_blocks_selects_and_names_the_insert_alternative_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1036
-- pg_mcp::tables::per_tool::live_tests::an_is_error_result_is_a_row_with_null_outputs
CREATE  FUNCTION live_tests."an_is_error_result_is_a_row_with_null_outputs"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'an_is_error_result_is_a_row_with_null_outputs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1241
-- pg_mcp::tables::per_tool::live_tests::t3_a_user_view_blocks_regeneration_with_restrict_and_nothing_is
CREATE  FUNCTION live_tests."t3_a_user_view_blocks_regeneration_with_restrict_and_nothing_is"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 't3_a_user_view_blocks_regeneration_with_restrict_and_nothing_is_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1181
-- pg_mcp::tables::per_tool::live_tests::unmappable_tools_are_reported_and_the_rest_generates
CREATE  FUNCTION live_tests."unmappable_tools_are_reported_and_the_rest_generates"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unmappable_tools_are_reported_and_the_rest_generates_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1329
-- pg_mcp::tables::per_tool::live_tests::generate_functions_returns_the_prd_tuple
CREATE  FUNCTION live_tests."generate_functions_returns_the_prd_tuple"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'generate_functions_returns_the_prd_tuple_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1012
-- pg_mcp::tables::per_tool::live_tests::missing_required_input_raises_22023_naming_the_argument
CREATE  FUNCTION live_tests."missing_required_input_raises_22023_naming_the_argument"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'missing_required_input_raises_22023_naming_the_argument_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1356
-- pg_mcp::tables::per_tool::live_tests::stale_tables_name_the_regeneration_fix
CREATE  FUNCTION live_tests."stale_tables_name_the_regeneration_fix"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stale_tables_name_the_regeneration_fix_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1096
-- pg_mcp::tables::per_tool::live_tests::t2_reserved_long_and_colliding_names_all_generate_and_are_query
CREATE  FUNCTION live_tests."t2_reserved_long_and_colliding_names_all_generate_and_are_query"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 't2_reserved_long_and_colliding_names_all_generate_and_are_query_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:1204
-- pg_mcp::tables::per_tool::live_tests::regeneration_drops_exactly_the_vanished_tools_objects
CREATE  FUNCTION live_tests."regeneration_drops_exactly_the_vanished_tools_objects"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'regeneration_drops_exactly_the_vanished_tools_objects_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:942
-- pg_mcp::tables::per_tool::live_tests::per_tool_tables_are_typed_and_invokable_end_to_end
CREATE  FUNCTION live_tests."per_tool_tables_are_typed_and_invokable_end_to_end"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_tool_tables_are_typed_and_invokable_end_to_end_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:848
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::tables::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:895
-- pg_mcp::tables::tests::tool_tables_carry_their_prd_columns_and_types
CREATE  FUNCTION tests."tool_tables_carry_their_prd_columns_and_types"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_tables_carry_their_prd_columns_and_types_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:1012
-- pg_mcp::tables::tests::track_b_handlers_declare_exactly_their_prd_pushdown_columns
CREATE  FUNCTION tests."track_b_handlers_declare_exactly_their_prd_pushdown_columns"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'track_b_handlers_declare_exactly_their_prd_pushdown_columns_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:922
-- pg_mcp::tables::tests::type_oids_agree_with_the_sql_spelling
CREATE  FUNCTION tests."type_oids_agree_with_the_sql_spelling"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'type_oids_agree_with_the_sql_spelling_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:949
-- pg_mcp::tables::tests::stub_handlers_scan_as_empty_and_refuse_inserts
CREATE  FUNCTION tests."stub_handlers_scan_as_empty_and_refuse_inserts"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stub_handlers_scan_as_empty_and_refuse_inserts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:943
-- pg_mcp::tables::tests::unknown_table_names_do_not_resolve
CREATE  FUNCTION tests."unknown_table_names_do_not_resolve"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unknown_table_names_do_not_resolve_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:1039
-- pg_mcp::tables::tests::insert_row_reads_by_column_name
CREATE  FUNCTION tests."insert_row_reads_by_column_name"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'insert_row_reads_by_column_name_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:873
-- pg_mcp::tables::tests::column_names_are_unique_and_non_empty_per_table
CREATE  FUNCTION tests."column_names_are_unique_and_non_empty_per_table"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'column_names_are_unique_and_non_empty_per_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:997
-- pg_mcp::tables::tests::stub_handlers_declare_no_pushdown
CREATE  FUNCTION tests."stub_handlers_declare_no_pushdown"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stub_handlers_declare_no_pushdown_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/mod.rs:853
-- pg_mcp::tables::tests::registry_holds_exactly_the_prd_tables
CREATE  FUNCTION tests."registry_holds_exactly_the_prd_tables"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'registry_holds_exactly_the_prd_tables_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1255
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::fdw::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1388
-- pg_mcp::fdw::tests::a_foreign_table_outside_the_registry_raises_0a000
CREATE  FUNCTION tests."a_foreign_table_outside_the_registry_raises_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_foreign_table_outside_the_registry_raises_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1378
-- pg_mcp::fdw::tests::update_and_delete_on_tool_calls_raise_0a000
CREATE  FUNCTION tests."update_and_delete_on_tool_calls_raise_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'update_and_delete_on_tool_calls_raise_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1399
-- pg_mcp::fdw::tests::explain_of_a_scan_does_not_execute_the_handler
CREATE  FUNCTION tests."explain_of_a_scan_does_not_execute_the_handler"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'explain_of_a_scan_does_not_execute_the_handler_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1364
-- pg_mcp::fdw::tests::insert_into_a_stub_table_raises_0a000
CREATE  FUNCTION tests."insert_into_a_stub_table_raises_0a000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'insert_into_a_stub_table_raises_0a000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1327
-- pg_mcp::fdw::tests::import_honors_limit_to_and_unknown_remote_schema_is_3f000
CREATE  FUNCTION tests."import_honors_limit_to_and_unknown_remote_schema_is_3f000"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_honors_limit_to_and_unknown_remote_schema_is_3f000_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1303
-- pg_mcp::fdw::tests::t5_import_creates_the_registry_tables_and_tools_scans_run_end_t
CREATE  FUNCTION tests."t5_import_creates_the_registry_tables_and_tools_scans_run_end_t"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 't5_import_creates_the_registry_tables_and_tools_scans_run_end_t_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fdw.rs:1350
-- pg_mcp::fdw::tests::a_role_without_a_user_mapping_still_scans_an_auth_none_server
CREATE  FUNCTION tests."a_role_without_a_user_mapping_still_scans_an_auth_none_server"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_role_without_a_user_mapping_still_scans_an_auth_none_server_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:145
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::quals::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:213
-- pg_mcp::quals::tests::restricted_values_flattens_sets
CREATE  FUNCTION tests."restricted_values_flattens_sets"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'restricted_values_flattens_sets_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:185
-- pg_mcp::quals::tests::other_columns_are_never_falsified
CREATE  FUNCTION tests."other_columns_are_never_falsified"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'other_columns_are_never_falsified_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:222
-- pg_mcp::quals::tests::fdw_private_round_trips_through_json
CREATE  FUNCTION tests."fdw_private_round_trips_through_json"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fdw_private_round_trips_through_json_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:195
-- pg_mcp::quals::tests::matches_json_semantics
CREATE  FUNCTION tests."matches_json_semantics"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'matches_json_semantics_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:166
-- pg_mcp::quals::tests::any_equal_with_zero_one_and_n_elements_is_supported
CREATE  FUNCTION tests."any_equal_with_zero_one_and_n_elements_is_supported"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'any_equal_with_zero_one_and_n_elements_is_supported_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:176
-- pg_mcp::quals::tests::nulls_and_nested_sets_are_unsupported
CREATE  FUNCTION tests."nulls_and_nested_sets_are_unsupported"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'nulls_and_nested_sets_are_unsupported_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/quals.rs:159
-- pg_mcp::quals::tests::equal_on_primitives_is_supported
CREATE  FUNCTION tests."equal_on_primitives_is_supported"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'equal_on_primitives_is_supported_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:686
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::tables::readthrough::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1312
-- pg_mcp::tables::readthrough::tests::unqualified_resource_contents_scan_raises_0a000_via_fdw
CREATE  FUNCTION tests."unqualified_resource_contents_scan_raises_0a000_via_fdw"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unqualified_resource_contents_scan_raises_0a000_via_fdw_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1405
-- pg_mcp::tables::readthrough::tests::read_through_errors_carry_server_and_method_in_detail
CREATE  FUNCTION tests."read_through_errors_carry_server_and_method_in_detail"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'read_through_errors_carry_server_and_method_in_detail_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:824
-- pg_mcp::tables::readthrough::tests::resource_contents_reads_once_per_distinct_uri
CREATE  FUNCTION tests."resource_contents_reads_once_per_distinct_uri"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'resource_contents_reads_once_per_distinct_uri_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1267
-- pg_mcp::tables::readthrough::tests::ap_p2_scans_issue_zero_tools_call_requests
CREATE  FUNCTION tests."ap_p2_scans_issue_zero_tools_call_requests"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ap_p2_scans_issue_zero_tools_call_requests_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1348
-- pg_mcp::tables::readthrough::tests::unqualified_resource_contents_at_cap_scans_via_fdw
CREATE  FUNCTION tests."unqualified_resource_contents_at_cap_scans_via_fdw"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unqualified_resource_contents_at_cap_scans_via_fdw_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:923
-- pg_mcp::tables::readthrough::tests::unqualified_resource_contents_cap_zero_message_is_verbatim
CREATE  FUNCTION tests."unqualified_resource_contents_cap_zero_message_is_verbatim"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unqualified_resource_contents_cap_zero_message_is_verbatim_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1000
-- pg_mcp::tables::readthrough::tests::prompt_messages_returns_messages_in_order
CREATE  FUNCTION tests."prompt_messages_returns_messages_in_order"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prompt_messages_returns_messages_in_order_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1105
-- pg_mcp::tables::readthrough::tests::completions_names_each_missing_qual
CREATE  FUNCTION tests."completions_names_each_missing_qual"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'completions_names_each_missing_qual_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1331
-- pg_mcp::tables::readthrough::tests::resource_contents_fanout_over_cap_raises_54023_via_fdw
CREATE  FUNCTION tests."resource_contents_fanout_over_cap_raises_54023_via_fdw"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'resource_contents_fanout_over_cap_raises_54023_via_fdw_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:889
-- pg_mcp::tables::readthrough::tests::resource_contents_meta_and_empty_any
CREATE  FUNCTION tests."resource_contents_meta_and_empty_any"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'resource_contents_meta_and_empty_any_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:978
-- pg_mcp::tables::readthrough::tests::prompt_messages_requires_a_prompt_qual
CREATE  FUNCTION tests."prompt_messages_requires_a_prompt_qual"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prompt_messages_requires_a_prompt_qual_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:808
-- pg_mcp::tables::readthrough::tests::base64_decode_round_trips
CREATE  FUNCTION tests."base64_decode_round_trips"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'base64_decode_round_trips_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1368
-- pg_mcp::tables::readthrough::tests::missing_quals_raise_0a000_via_fdw
CREATE  FUNCTION tests."missing_quals_raise_0a000_via_fdw"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'missing_quals_raise_0a000_via_fdw_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1146
-- pg_mcp::tables::readthrough::tests::completions_returns_candidates_with_idx_total_has_more
CREATE  FUNCTION tests."completions_returns_candidates_with_idx_total_has_more"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'completions_returns_candidates_with_idx_total_has_more_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:939
-- pg_mcp::tables::readthrough::tests::unqualified_resource_contents_honors_the_cap_boundary
CREATE  FUNCTION tests."unqualified_resource_contents_honors_the_cap_boundary"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unqualified_resource_contents_honors_the_cap_boundary_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:1079
-- pg_mcp::tables::readthrough::tests::prompt_messages_defaults_arguments_to_empty_object
CREATE  FUNCTION tests."prompt_messages_defaults_arguments_to_empty_object"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prompt_messages_defaults_arguments_to_empty_object_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/readthrough.rs:768
-- pg_mcp::tables::readthrough::tests::restricted_intersects_and_dedupes
CREATE  FUNCTION tests."restricted_intersects_and_dedupes"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'restricted_intersects_and_dedupes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:489
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:697
-- pg_mcp::codegen::tests::unmappable_tools_are_skipped_not_fatal
CREATE  FUNCTION tests."unmappable_tools_are_skipped_not_fatal"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unmappable_tools_are_skipped_not_fatal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:805
-- pg_mcp::codegen::tests::title_and_description_are_carried_for_comments
CREATE  FUNCTION tests."title_and_description_are_carried_for_comments"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'title_and_description_are_carried_for_comments_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:798
-- pg_mcp::codegen::tests::empty_target_schema_is_rejected
CREATE  FUNCTION tests."empty_target_schema_is_rejected"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'empty_target_schema_is_rejected_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:768
-- pg_mcp::codegen::tests::per_tool_column_collisions_get_property_hash_suffixes
CREATE  FUNCTION tests."per_tool_column_collisions_get_property_hash_suffixes"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_tool_column_collisions_get_property_hash_suffixes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:717
-- pg_mcp::codegen::tests::unnamed_tools_are_skipped
CREATE  FUNCTION tests."unnamed_tools_are_skipped"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unnamed_tools_are_skipped_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:509
-- pg_mcp::codegen::tests::the_prd_example_tool_plans_exactly
CREATE  FUNCTION tests."the_prd_example_tool_plans_exactly"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'the_prd_example_tool_plans_exactly_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:786
-- pg_mcp::codegen::tests::prefix_lands_on_the_derived_object_names
CREATE  FUNCTION tests."prefix_lands_on_the_derived_object_names"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prefix_lands_on_the_derived_object_names_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:646
-- pg_mcp::codegen::tests::invocation_gate_follows_the_prd_matrix
CREATE  FUNCTION tests."invocation_gate_follows_the_prd_matrix"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'invocation_gate_follows_the_prd_matrix_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:576
-- pg_mcp::codegen::tests::output_shape_matrix_matches_prd_4_2
CREATE  FUNCTION tests."output_shape_matrix_matches_prd_4_2"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'output_shape_matrix_matches_prd_4_2_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/mod.rs:726
-- pg_mcp::codegen::tests::per_upstream_routing_splits_schemas_and_strips_prefixes
CREATE  FUNCTION tests."per_upstream_routing_splits_schemas_and_strips_prefixes"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_upstream_routing_splits_schemas_and_strips_prefixes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:149
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::sse::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:217
-- pg_mcp::sse::tests::truncated_stream_is_08006
CREATE  FUNCTION tests."truncated_stream_is_08006"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'truncated_stream_is_08006_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:191
-- pg_mcp::sse::tests::skips_frames_for_other_ids_and_notifications
CREATE  FUNCTION tests."skips_frames_for_other_ids_and_notifications"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'skips_frames_for_other_ids_and_notifications_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:231
-- pg_mcp::sse::tests::non_json_frames_are_skipped_not_fatal
CREATE  FUNCTION tests."non_json_frames_are_skipped_not_fatal"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'non_json_frames_are_skipped_not_fatal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:329
-- pg_mcp::sse::tests::observer_panics_do_not_bypass_the_match
CREATE  FUNCTION tests."observer_panics_do_not_bypass_the_match"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'observer_panics_do_not_bypass_the_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:245
-- pg_mcp::sse::tests::deadline_is_total_across_the_stream
CREATE  FUNCTION tests."deadline_is_total_across_the_stream"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'deadline_is_total_across_the_stream_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:157
-- pg_mcp::sse::tests::single_event
CREATE  FUNCTION tests."single_event"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'single_event_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:280
-- pg_mcp::sse::tests::a_cancelling_interrupt_hook_aborts_the_read
CREATE  FUNCTION tests."a_cancelling_interrupt_hook_aborts_the_read"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'a_cancelling_interrupt_hook_aborts_the_read_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:167
-- pg_mcp::sse::tests::multi_line_data_is_joined_with_newlines
CREATE  FUNCTION tests."multi_line_data_is_joined_with_newlines"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'multi_line_data_is_joined_with_newlines_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:292
-- pg_mcp::sse::tests::observer_sees_skipped_frames_including_notifications
CREATE  FUNCTION tests."observer_sees_skipped_frames_including_notifications"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'observer_sees_skipped_frames_including_notifications_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:207
-- pg_mcp::sse::tests::string_ids_still_match
CREATE  FUNCTION tests."string_ids_still_match"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'string_ids_still_match_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:224
-- pg_mcp::sse::tests::stream_without_the_wanted_id_is_08006
CREATE  FUNCTION tests."stream_without_the_wanted_id_is_08006"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'stream_without_the_wanted_id_is_08006_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:175
-- pg_mcp::sse::tests::ignores_comments_event_and_id_lines
CREATE  FUNCTION tests."ignores_comments_event_and_id_lines"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ignores_comments_event_and_id_lines_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/sse.rs:260
-- pg_mcp::sse::tests::interrupt_hook_runs_between_events
CREATE  FUNCTION tests."interrupt_hook_runs_between_events"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'interrupt_hook_runs_between_events_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:386
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::import::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:513
-- pg_mcp::import::tests::cache_ttl_ms_accepts_number_and_string_forms
CREATE  FUNCTION tests."cache_ttl_ms_accepts_number_and_string_forms"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cache_ttl_ms_accepts_number_and_string_forms_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:630
-- pg_mcp::import::tests::per_tool_plan_honors_prefix_and_cache_ttl
CREATE  FUNCTION tests."per_tool_plan_honors_prefix_and_cache_ttl"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_tool_plan_honors_prefix_and_cache_ttl_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:693
-- pg_mcp::import::tests::engine_local_tables_are_exactly_server_and_tool_calls
CREATE  FUNCTION tests."engine_local_tables_are_exactly_server_and_tool_calls"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'engine_local_tables_are_exactly_server_and_tool_calls_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:648
-- pg_mcp::import::tests::per_upstream_layout_creates_schemas_and_marks_slices
CREATE  FUNCTION tests."per_upstream_layout_creates_schemas_and_marks_slices"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_upstream_layout_creates_schemas_and_marks_slices_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:718
-- pg_mcp::import::tests::t1_engine_layout_creates_one_schema_per_upstream_plus_the_engin
CREATE  FUNCTION tests."t1_engine_layout_creates_one_schema_per_upstream_plus_the_engin"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 't1_engine_layout_creates_one_schema_per_upstream_plus_the_engin_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:764
-- pg_mcp::import::tests::engine_layout_combines_upstream_and_cache_ttl_options
CREATE  FUNCTION tests."engine_layout_combines_upstream_and_cache_ttl_options"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'engine_layout_combines_upstream_and_cache_ttl_options_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:589
-- pg_mcp::import::tests::per_tool_plan_emits_the_full_object_set
CREATE  FUNCTION tests."per_tool_plan_emits_the_full_object_set"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'per_tool_plan_emits_the_full_object_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:437
-- pg_mcp::import::tests::identifiers_are_quoted
CREATE  FUNCTION tests."identifiers_are_quoted"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'identifiers_are_quoted_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:526
-- pg_mcp::import::tests::bad_import_options_are_rejected
CREATE  FUNCTION tests."bad_import_options_are_rejected"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'bad_import_options_are_rejected_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:675
-- pg_mcp::import::tests::cache_ttl_lands_in_every_tables_options
CREATE  FUNCTION tests."cache_ttl_lands_in_every_tables_options"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'cache_ttl_lands_in_every_tables_options_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:504
-- pg_mcp::import::tests::import_options_default_to_empty_and_null_is_accepted
CREATE  FUNCTION tests."import_options_default_to_empty_and_null_is_accepted"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_options_default_to_empty_and_null_is_accepted_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:563
-- pg_mcp::import::tests::prd8_import_options_parse_to_their_defaults_and_values
CREATE  FUNCTION tests."prd8_import_options_parse_to_their_defaults_and_values"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'prd8_import_options_parse_to_their_defaults_and_values_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:447
-- pg_mcp::import::tests::every_statement_projects_its_spec_exactly
CREATE  FUNCTION tests."every_statement_projects_its_spec_exactly"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'every_statement_projects_its_spec_exactly_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:703
-- pg_mcp::import::tests::upstream_prefixes_come_from_the_tools_list_namespacing
CREATE  FUNCTION tests."upstream_prefixes_come_from_the_tools_list_namespacing"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'upstream_prefixes_come_from_the_tools_list_namespacing_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:398
-- pg_mcp::import::tests::limit_to_and_except_filter_by_table_name
CREATE  FUNCTION tests."limit_to_and_except_filter_by_table_name"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'limit_to_and_except_filter_by_table_name_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:782
-- pg_mcp::import::tests::engine_layout_quotes_odd_upstream_names
CREATE  FUNCTION tests."engine_layout_quotes_odd_upstream_names"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'engine_layout_quotes_odd_upstream_names_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:390
-- pg_mcp::import::tests::all_emits_one_statement_per_registry_table
CREATE  FUNCTION tests."all_emits_one_statement_per_registry_table"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'all_emits_one_statement_per_registry_table_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:477
-- pg_mcp::import::tests::server_table_ddl_is_exact
CREATE  FUNCTION tests."server_table_ddl_is_exact"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'server_table_ddl_is_exact_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/import.rs:415
-- pg_mcp::import::tests::tool_calls_ddl_matches_the_prd_column_block
CREATE  FUNCTION tests."tool_calls_ddl_matches_the_prd_column_block"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'tool_calls_ddl_matches_the_prd_column_block_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:493
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::api::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:643
-- pg_mcp::api::tests::import_unknown_server_raises_42704
CREATE  FUNCTION tests."import_unknown_server_raises_42704"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_unknown_server_raises_42704_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:575
-- pg_mcp::api::tests::import_twice_in_one_backend_and_once_more_failing
CREATE  FUNCTION tests."import_twice_in_one_backend_and_once_more_failing"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_twice_in_one_backend_and_once_more_failing_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:652
-- pg_mcp::api::tests::import_all_upstreams_needs_a_reachable_engine
CREATE  FUNCTION tests."import_all_upstreams_needs_a_reachable_engine"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_all_upstreams_needs_a_reachable_engine_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:597
-- pg_mcp::api::tests::import_cache_ttl_option_is_visible_in_the_catalog
CREATE  FUNCTION tests."import_cache_ttl_option_is_visible_in_the_catalog"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_cache_ttl_option_is_visible_in_the_catalog_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:617
-- pg_mcp::api::tests::import_rejects_bad_options
CREATE  FUNCTION tests."import_rejects_bad_options"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_rejects_bad_options_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:545
-- pg_mcp::api::tests::import_returns_the_count_and_creates_the_tables
CREATE  FUNCTION tests."import_returns_the_count_and_creates_the_tables"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_returns_the_count_and_creates_the_tables_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:105
CREATE SCHEMA IF NOT EXISTS mcp; /* pg_mcp::mcp */
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:109
-- pg_mcp::mcp::version
CREATE  FUNCTION mcp."version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:115
-- pg_mcp::mcp::protocol_version
CREATE  FUNCTION mcp."protocol_version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'protocol_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:395
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::session::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:407
-- pg_mcp::session::tests::validator_option_array_splits_on_the_first_equals
CREATE  FUNCTION tests."validator_option_array_splits_on_the_first_equals"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'validator_option_array_splits_on_the_first_equals_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:447
-- pg_mcp::session::tests::current_user_oid_is_a_real_role
CREATE  FUNCTION tests."current_user_oid_is_a_real_role"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'current_user_oid_is_a_real_role_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:441
-- pg_mcp::session::tests::dropping_an_absent_session_reports_false
CREATE  FUNCTION tests."dropping_an_absent_session_reports_false"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'dropping_an_absent_session_reports_false_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:400
-- pg_mcp::session::tests::unknown_foreign_server_is_42704
CREATE  FUNCTION tests."unknown_foreign_server_is_42704"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'unknown_foreign_server_is_42704_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:424
-- pg_mcp::session::tests::params_object_defaults_to_empty
CREATE  FUNCTION tests."params_object_defaults_to_empty"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'params_object_defaults_to_empty_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/session.rs:431
-- pg_mcp::session::tests::session_map_starts_empty_in_a_fresh_backend
CREATE  FUNCTION tests."session_map_starts_empty_in_a_fresh_backend"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_map_starts_empty_in_a_fresh_backend_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:543
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::tables::per_tool::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:550
-- pg_mcp::tables::per_tool::tests::json_values_convert_to_typed_cells
CREATE  FUNCTION tests."json_values_convert_to_typed_cells"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'json_values_convert_to_typed_cells_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/tables/per_tool.rs:606
-- pg_mcp::tables::per_tool::tests::timestamptz_round_trips_through_the_wire_form
CREATE  FUNCTION tests."timestamptz_round_trips_through_the_wire_form"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'timestamptz_round_trips_through_the_wire_form_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/registry.rs:207
CREATE SCHEMA IF NOT EXISTS tests; /* pg_mcp::codegen::registry::tests */
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/registry.rs:224
-- pg_mcp::codegen::registry::tests::drop_statements_are_restrict_per_kind
CREATE  FUNCTION tests."drop_statements_are_restrict_per_kind"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'drop_statements_are_restrict_per_kind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/registry.rs:254
-- pg_mcp::codegen::registry::tests::record_lookup_and_drop_owned_round_trip
CREATE  FUNCTION tests."record_lookup_and_drop_owned_round_trip"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'record_lookup_and_drop_owned_round_trip_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/codegen/registry.rs:213
-- pg_mcp::codegen::registry::tests::the_bookkeeping_shape_holds_names_and_provenance_only
CREATE  FUNCTION tests."the_bookkeeping_shape_holds_names_and_provenance_only"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'the_bookkeeping_shape_holds_names_and_provenance_only_wrapper';
/* </end connected objects> */

