/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:242
-- pg_mcp::api::mcp_fdw_validator
CREATE  FUNCTION "mcp_fdw_validator"(
	"options" TEXT[], /* Vec < Option < String > > */
	"catalog" oid /* Oid */
) RETURNS void
STRICT 
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'mcp_fdw_validator_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:37
-- requires:
--   api::mcp_fdw_validator


-- This hand-written block is emitted before pgrx's `#[pg_schema]` statements,
-- so the schema must exist before the FDW function below lands in it. The
-- later `CREATE SCHEMA IF NOT EXISTS mcp` from the schema modules then skips
-- cleanly (an object the extension already owns).
CREATE SCHEMA IF NOT EXISTS mcp;

-- FR-6.3: register the mcp_fdw foreign-data wrapper so CREATE SERVER and
-- CREATE USER MAPPING run their option validators. The handler's scan/modify
-- routines are PRD-7; planning against a foreign table raises 0A000 today.
--
-- The validator's Rust body is `api::mcp_fdw_validator` (`#[pg_extern]`); its
-- CREATE FUNCTION is written here because `CREATE FOREIGN DATA WRAPPER` below
-- needs it before pgrx emits the schema modules. pgrx later re-emits the same
-- signature as CREATE OR REPLACE FUNCTION, which is a no-op here.
CREATE FUNCTION mcp.mcp_fdw_validator(text[], oid)
  RETURNS void
  AS 'MODULE_PATHNAME', 'mcp_fdw_validator_wrapper'
  LANGUAGE C;

CREATE FUNCTION mcp.mcp_fdw_handler()
  RETURNS fdw_handler
  AS 'MODULE_PATHNAME', 'mcp_fdw_handler'
  LANGUAGE C STRICT;

CREATE FOREIGN DATA WRAPPER mcp_fdw
  HANDLER mcp.mcp_fdw_handler
  VALIDATOR mcp.mcp_fdw_validator;

COMMENT ON FOREIGN DATA WRAPPER mcp_fdw IS
  'Model Context Protocol servers as Postgres foreign servers (pg_mcp)';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:74
CREATE SCHEMA IF NOT EXISTS mcp; /* pg_mcp::api::mcp */
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:123
-- pg_mcp::api::mcp::complete
CREATE  FUNCTION mcp."complete"(
	"server" TEXT, /* & str */
	"r#ref" jsonb, /* JsonB */
	"argument_name" TEXT, /* & str */
	"argument_value" TEXT /* & str */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:179
-- pg_mcp::api::mcp::session_count
CREATE  FUNCTION mcp."session_count"() RETURNS INT /* i32 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:94
-- pg_mcp::api::mcp::call_tool_text
CREATE  FUNCTION mcp."call_tool_text"(
	"server" TEXT, /* & str */
	"tool" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb, /* Option < JsonB > */
	"on_error" TEXT DEFAULT 'raise' /* & str */
) RETURNS TEXT /* Option < String > */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'call_tool_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:137
-- pg_mcp::api::mcp::refresh
CREATE  FUNCTION mcp."refresh"(
	"server" TEXT /* & str */
) RETURNS bool /* bool */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'refresh_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:106
-- pg_mcp::api::mcp::get_prompt
CREATE  FUNCTION mcp."get_prompt"(
	"server" TEXT, /* & str */
	"prompt" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'get_prompt_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:153
-- pg_mcp::api::mcp::import
CREATE  FUNCTION mcp."import"(
	"server" TEXT, /* & str */
	"schema" TEXT, /* & str */
	"opts" jsonb DEFAULT '{}'::jsonb /* Option < JsonB > */
) RETURNS INT /* i32 */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'import_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:82
-- pg_mcp::api::mcp::call_tool
CREATE  FUNCTION mcp."call_tool"(
	"server" TEXT, /* & str */
	"tool" TEXT, /* & str */
	"args" jsonb DEFAULT '{}'::jsonb, /* Option < JsonB > */
	"on_error" TEXT DEFAULT 'raise' /* & str */
) RETURNS jsonb /* JsonB */
VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'call_tool_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:169
-- pg_mcp::api::mcp::session_initialize_count
CREATE  FUNCTION mcp."session_initialize_count"(
	"server" TEXT /* & str */
) RETURNS INT /* Option < i32 > */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_initialize_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:117
-- pg_mcp::api::mcp::read_resource
CREATE  FUNCTION mcp."read_resource"(
	"server" TEXT, /* & str */
	"uri" TEXT /* & str */
) RETURNS jsonb /* JsonB */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'read_resource_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api.rs:186
-- pg_mcp::api::mcp::session_info
CREATE  FUNCTION mcp."session_info"(
	"server" TEXT /* & str */
) RETURNS jsonb /* Option < JsonB > */
STRICT VOLATILE PARALLEL UNSAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'session_info_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:76
CREATE SCHEMA IF NOT EXISTS mcp; /* pg_mcp::mcp */
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:86
-- pg_mcp::mcp::protocol_version
CREATE  FUNCTION mcp."protocol_version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'protocol_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:80
-- pg_mcp::mcp::version
CREATE  FUNCTION mcp."version"() RETURNS TEXT /* & '_ str */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'version_wrapper';
/* </end connected objects> */

